apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - image: nginx
        name: nginx