apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: software-studio-apps
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  description: TheBAH Software Studio APP of APPs PRoject

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'